### ISSUE TITLE
jquery.ui.pos.js is not compatible with requirejs

### ISSUE THREAD

**Issue by jojoob** [farbelous/fontawesome-iconpicker#29]
While iconpicker.js is compatible with requirejs thanks to the special factory function jquery.ui.pos.js is not. This makes it unable to load the iconpicker in whole with requirejs without further modifications.

The solution I have chosen is wrapping the jquery.ui.pos.js into the same requirejs compatible factory function as iconpicker.js and then add jquery.ui.pos.js as an requirement for iconpicker.js.

**Comment by itsjavi** [comment]
This should have been fixed when we updated jquery.ui last year

**Comment by ian-weatherhogg-refractiv** [comment]
trying to upgrade from v1.3.0 to v3.0.0 or v.3.2.0 but it's no longer working with requirejs.
when it's been loaded, there's no function $.iconpicker
(using jquery 3.2.1 and bootstrap 3.3.7 but those are unchanged)
