### ISSUE TITLE
When not inline the control is eating mouseup events from parts of the page unrelated to the icon picker

### ISSUE THREAD

**Issue by cck0001** [farbelous/fontawesome-iconpicker#35]
I have a canvas app and the interface allows you to pan around the canvas while the mouse is down. I integrated the fontawesome-iconpicker in an unrelated div and because the binding is at the doc layer it began eating mouseup events everywhere even when the icon picker is not visible. As a result the user gets stuck in pan. If I comment out the mouseup event eating then it all works well:

                b.on("mouseup" + d, function(a) {
                    if (!c._isEventInsideIconpicker(a) && !c.isInline()) {
                        c.hide();
                    }
                    // a.stopPropagation();
                    // a.preventDefault();
                    // return false;
                    return true;
                });

**Comment by itsjavi** [comment]
this is fixed on v3
thanks
