### ISSUE TITLE
Display Button in Plain Text Field

### ISSUE THREAD

**Issue by jready16** [farbelous/fontawesome-iconpicker#49]
Dumb question, but I can't figure out how to display the button along the right side of the plain text field like it's shown in this image from the Drupal page. Does anybody know how to implement this?
![image](https://user-images.githubusercontent.com/21961051/29095324-673bb516-7c5e-11e7-9896-381dbf593bfd.png)

**Comment by itsjavi** [comment]
you have the example in the plugin site "As a component" https://farbelous.github.io/fontawesome-iconpicker/
