### ISSUE TITLE
Icon picker not show when clicked

### ISSUE THREAD

**Issue by blackinitial** [farbelous/fontawesome-iconpicker#52]
![screenshot_2017-08-29_08-22-57](https://user-images.githubusercontent.com/21137500/29800510-aeec7c7e-8c94-11e7-95d9-7e0b239fb701.png)
![screenshot_2017-08-29_08-26-49](https://user-images.githubusercontent.com/21137500/29800500-a40c94a6-8c94-11e7-8d94-b9c6063cde52.png)

why picker not show, opacity in class .fade not change to 1 .

**Comment by amandadoughty** [comment]
This may be due to:
Turns out this is a compatibilty between jQuery 3.x.x and jQueryUI prior to 1.12.0.
If you want to use jQuery 3.x.x, use jQueryUI 1.12.0 or higher.

Stack trace:

TypeError: f.getClientRects is not a function[Learn More]  jquery-3.1.0.min.js:4:20033
	.offset http://moodle.city.ac.uk/theme/jquery.php/core/jquery-3.1.0.min.js:4:20033
	a.pos.getWithinInfo http://moodle.city.ac.uk/mod/bootstrapelements/js/fontawesome-iconpicker.min.js:1:1498
	a.fn.pos http://moodle.city.ac.uk/mod/bootstrapelements/js/fontawesome-iconpicker.min.js:1:1757
	c.prototype.updatePlacement http://moodle.city.ac.uk/mod/bootstrapelements/js/fontawesome-iconpicker.min.js:1:14979
	c.prototype.show http://moodle.city.ac.uk/mod/bootstrapelements/js/fontawesome-iconpicker.min.js:1:17782
	c.prototype._bindElementEvents/< http://moodle.city.ac.uk/mod/bootstrapelements/js/fontawesome-iconpicker.min.js:1:12283
	r.event.dispatch http://moodle.city.ac.uk/theme/jquery.php/core/jquery-3.1.0.min.js:3:9870
	r.event.add/q.handle http://moodle.city.ac.uk/theme/jquery.php/core/jquery-3.1.0.min.js:3:7932

**Comment by amandadoughty** [comment]
Perhaps jquery.ui.pos.js is based on a pre-1.12.0 jQueryUI?

**Comment by blackinitial** [comment]
i already use jquery 3.2.1 and jqueryui 1.12.1,
but there is still an error if click, TypeError: f.getClientRects is not a function

**Comment by itsjavi** [comment]
This should be fixed in `1.3.1` :)

**Comment by blackinitial** [comment]
it's so work, thanks a lot @itsjavi

**Comment by cheborneck** [comment]
Having a problem getting the picker to display. I have jquery ui 1.12.1 and jquery 3.1.1. Can't see all of the generated code in the developer but it does nothing when I click the input.

**Comment by yurayakimenko** [comment]
> This should be fixed in `1.3.1` :)
Nice.. should be fixed in `1.3.1` version of what component? `fontawesome-iconpicker` seems to not to have any versioning. please specify what component did you mean?
