### ISSUE TITLE
iconpicker input box not triggering change or input events?

### ISSUE THREAD

**Issue by hplato** [farbelous/fontawesome-iconpicker#54]
I might be doing something wrong, but I have the icon picker in a form:

   ` <form class='form-horizontal d-edit'>`
  ` <div class="form-group"><label for="icon" class="control-label col-sm-2">Icon</label><div class="col-sm-10">`
    `<div class="input-group dev-icon"><span class="input-group-addon" id="icon_gylph">X</span>
    <input type="text" class="form-control iconpicker" id="icon" value="value"></div></div></div>`

I have other text inputs in this form, and these jquery events work perfect, but they don't fire off when iconpicker puts a new icon in the '#icon' text box. Am I doing something wrong?

                $('.d-edit').on('change', function () {
                });
 
                 $('.d-edit').on('input', function () {
                });

**Comment by itsjavi** [comment]
The plugin doesn't interfere with the standard DOM events like `change`, so you may need to implement something in your own to support that.

Here you can see a list of what events are triggered from the plugin side: https://github.com/farbelous/fontawesome-iconpicker#triggered-events
