### ISSUE TITLE
How to destroy just 1 instance only? How to icon picker working on jQuery .clone() too?

### ISSUE THREAD

**Issue by topex-psy** [farbelous/fontawesome-iconpicker#57]
There's no example in documentation except for destroying all instances at once. My main aim now is I want to element which containing iconpicker & cloned with jQuery works too. How to do that?

**Comment by anwardote** [comment]
No solutions?

**Comment by itsjavi** [comment]
try `$('#mypicker').data('iconpicker').destroy();`
