### ISSUE TITLE
add support for synonyms

### ISSUE THREAD

**Issue by Blakko** [farbelous/fontawesome-iconpicker#59]
Would it be possible to add synonyms to search icons?

**Comment by itsjavi** [comment]
I think so, if you modify the plugin to "translate" those synonyms into real FA icons, but that's not something I am considering to add. I want to keep it simple.

**Comment by itsjavi** [comment]
you only need to add them to the `options.icons` array.

**Comment by itsjavi** [comment]
FYI, this is now supported via searchTerms and some synonyms are bundled by default, using the official Font Awesome search terms.
