### ISSUE TITLE
How can I remove selected icon as initial state?

### ISSUE THREAD

**Issue by alex-kowalski** [farbelous/fontawesome-iconpicker#60]
Hello!

This fontawesome-iconpicker is good and I like to use this.
I think one thing is missed.
Once I chose icon, how can i cancel it as initial state?
I have looked something, but not found yet.
Please let me know.

Thanks.
Best Regards

**Comment by inet123** [comment]
I'm not sure If I fully understand you, but you can change the selected icon in any moment by calling
'''
$('.my').data('iconpicker').update('fa-file'); // for example, can be any icon
'''

**Comment by alex-kowalski** [comment]
Thanks for your response.

I mean clearing selected icon.

Initially there is no selected icon, and input field is empty.

![image](https://user-images.githubusercontent.com/26298736/36074732-142ed3fc-0ef9-11e8-9c0b-dc4db1f6712c.png)


But once icon selected, how can i remove selected icon as same as initial state.
I also tried as below, but it seems not working.

$('.my').data('iconpicker').update('');

maybe this clearing function was missed?

**Comment by remijean** [comment]
@alex-kowalski reset alternative : 

// Init
var options = {};
 $("#foo").iconpicker(options);

...

// Reset
$("#bar").on("click", function() {
    $("#foo").data("iconpicker").destroy();
    $("#foo").iconpicker(options);
});

**Comment by alex-kowalski** [comment]
@remijean thanks for your reply
