### ISSUE TITLE
How to show only fontawesome 4 icons ?

### ISSUE THREAD

**Issue by DiegoFelipe** [farbelous/fontawesome-iconpicker#72]
I only want to show fontawesome 4 icons, I don't want 'fab','fas','far' icons, just 'fa'. I already tried it:

`icons: [], // list of icon objects [{title:String, searchTerms:String}]. By default, all Font Awesome icons are included.
    fullClassFormatter: function(val) {
        return 'fa ' + val;
    },`

But it didn't worked.

Thanks in regard

**Comment by itsjavi** [comment]
You need to use v1.4.1 for that.

From v2.0.0 on, only Font Awesome 5 is supported

please check the releases
https://github.com/farbelous/fontawesome-iconpicker/releases
