### ISSUE TITLE
Drupal 8 support

### ISSUE THREAD

**Issue by szepeviktor** [farbelous/fontawesome-iconpicker#85]
It would be great to add Drupal 8 library download support as colorbox does.

https://cgit.drupalcode.org/colorbox/tree/README.txt#n98

**Comment by szepeviktor** [comment]
There are such a thing as `"type:drupal-library"` in composer.

**Comment by itsjavi** [comment]
sorry but this is not a drupal library,
if needed, you should create a separate repo with a composer.json in it like this: https://cgit.drupalcode.org/colorbox/tree/composer.json
