### ISSUE TITLE
Font Awesome 5 Pro

### ISSUE THREAD

**Issue by chille1987** [farbelous/fontawesome-iconpicker#87]
Here is the file with all Font Awesome Pro icons included. I've manually added all the icons in fontawesome-iconpicker.js file. You still need a Pro licence to use it in your project but this will save time.

[fontawesome-pro-icons.zip](https://github.com/farbelous/fontawesome-iconpicker/files/2658780/fontawesome-pro-icons.zip)

**Comment by itsjavi** [comment]
this is duplicate of your previous ticket:
https://github.com/farbelous/fontawesome-iconpicker/issues/84
please continue the discussion there
