### ISSUE TITLE
Project Take Over: Looking for experienced front-end devs

### ISSUE THREAD

**Issue by itsjavi** [farbelous/fontawesome-iconpicker#90]
I am looking for experienced frontend developers with enough experience in JS, WebPack, React (and the tooling used in this project) that volunteer in taking over the project development and maintenance.

Unfortunately I don't have time to dedicate to this project anymore, since I am basically the only developer and Pull Requests from other people to fix bugs don't happen very often.

Please apply here if you are interested, with links to your projects or projects you have contributed to.

I will be happy to make you a maintainer of this project. You will also have rights to publish new versions in npm and Chrome Extensions (accounts are required in both services).

If there are no enough experienced volunteers until the **1st of May**, this project will go under "**archive**" mode, meaning that it will be in "read-only" mode and no more issues will be able to be created.

Thank you to all users and contributors using this library all these years,

Javier.

**UPDATE of 09 May 2019: This project has been archived. If you want to take it over please contact me. You can find me at https://itsjavi.com**

**Comment by Arielblues** [comment]
I just saw your comment. I cannot maintain the project case i am not experienced enough with all above.
